package ssm.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ssm.mybatis.po.Grouplink;
import ssm.mybatis.po.GrouplinkExample;

public interface GrouplinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouplink
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    long countByExample(GrouplinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouplink
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int deleteByExample(GrouplinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouplink
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int insert(Grouplink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouplink
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int insertSelective(Grouplink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouplink
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    List<Grouplink> selectByExample(GrouplinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouplink
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") Grouplink record, @Param("example") GrouplinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouplink
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int updateByExample(@Param("record") Grouplink record, @Param("example") GrouplinkExample example);
}