package ssm.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ssm.mybatis.po.Sharefile;
import ssm.mybatis.po.SharefileExample;

public interface SharefileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sharefile
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    long countByExample(SharefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sharefile
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int deleteByExample(SharefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sharefile
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int insert(Sharefile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sharefile
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int insertSelective(Sharefile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sharefile
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    List<Sharefile> selectByExample(SharefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sharefile
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sharefile record, @Param("example") SharefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sharefile
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    int updateByExample(@Param("record") Sharefile record, @Param("example") SharefileExample example);
}