package ssm.mybatis.po;

public class Grouplink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grouplink.id
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grouplink.groupid
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private Integer groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grouplink.usersid
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private Integer usersid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grouplink.id
     *
     * @return the value of t_grouplink.id
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grouplink.id
     *
     * @param id the value for t_grouplink.id
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grouplink.groupid
     *
     * @return the value of t_grouplink.groupid
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grouplink.groupid
     *
     * @param groupid the value for t_grouplink.groupid
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grouplink.usersid
     *
     * @return the value of t_grouplink.usersid
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public Integer getUsersid() {
        return usersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grouplink.usersid
     *
     * @param usersid the value for t_grouplink.usersid
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setUsersid(Integer usersid) {
        this.usersid = usersid;
    }
}