package ssm.mybatis.po;

public class Sharefile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.id
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.userid
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.filename
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.filepath
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.type
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.http
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String http;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.pwd
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.isdir
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String isdir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.filelength
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String filelength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sharefile.data
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.id
     *
     * @return the value of t_sharefile.id
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.id
     *
     * @param id the value for t_sharefile.id
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.userid
     *
     * @return the value of t_sharefile.userid
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.userid
     *
     * @param userid the value for t_sharefile.userid
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.filename
     *
     * @return the value of t_sharefile.filename
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.filename
     *
     * @param filename the value for t_sharefile.filename
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.filepath
     *
     * @return the value of t_sharefile.filepath
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.filepath
     *
     * @param filepath the value for t_sharefile.filepath
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.type
     *
     * @return the value of t_sharefile.type
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.type
     *
     * @param type the value for t_sharefile.type
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.http
     *
     * @return the value of t_sharefile.http
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getHttp() {
        return http;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.http
     *
     * @param http the value for t_sharefile.http
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setHttp(String http) {
        this.http = http == null ? null : http.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.pwd
     *
     * @return the value of t_sharefile.pwd
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.pwd
     *
     * @param pwd the value for t_sharefile.pwd
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.isdir
     *
     * @return the value of t_sharefile.isdir
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getIsdir() {
        return isdir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.isdir
     *
     * @param isdir the value for t_sharefile.isdir
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setIsdir(String isdir) {
        this.isdir = isdir == null ? null : isdir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.filelength
     *
     * @return the value of t_sharefile.filelength
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getFilelength() {
        return filelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.filelength
     *
     * @param filelength the value for t_sharefile.filelength
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setFilelength(String filelength) {
        this.filelength = filelength == null ? null : filelength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sharefile.data
     *
     * @return the value of t_sharefile.data
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sharefile.data
     *
     * @param data the value for t_sharefile.data
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}