package ssm.mybatis.po;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.realname
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.joindate
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String joindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.lastdate
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private String lastdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.capacity
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    private Integer capacity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.realname
     *
     * @return the value of t_user.realname
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.realname
     *
     * @param realname the value for t_user.realname
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.joindate
     *
     * @return the value of t_user.joindate
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getJoindate() {
        return joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.joindate
     *
     * @param joindate the value for t_user.joindate
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setJoindate(String joindate) {
        this.joindate = joindate == null ? null : joindate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.lastdate
     *
     * @return the value of t_user.lastdate
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public String getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.lastdate
     *
     * @param lastdate the value for t_user.lastdate
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setLastdate(String lastdate) {
        this.lastdate = lastdate == null ? null : lastdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.capacity
     *
     * @return the value of t_user.capacity
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.capacity
     *
     * @param capacity the value for t_user.capacity
     *
     * @mbg.generated Mon Jun 11 17:54:05 CST 2018
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

	@Override
	public String toString() {
		return "User [id=" + id + ", username=" + username + ", realname=" + realname + ", email=" + email
				+ ", password=" + password + ", joindate=" + joindate + ", lastdate=" + lastdate + ", capacity="
				+ capacity + "]";
	}
    
}
